CREATE TABLE tUnitType
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name VARCHAR(50) NOT NULL,
  CONSTRAINT UN_Name UNIQUE (Name)
);

INSERT INTO tUnitType(Name)
SELECT 'each'
UNION ALL 
SELECT 'bundle'
UNION ALL 
SELECT 'bunch'
UNION ALL 
SELECT 'box'
UNION ALL 
SELECT 'set'
UNION ALL 
SELECT 'container'
UNION ALL 
SELECT 'case';

CREATE TABLE tProduct
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name VARCHAR(50), 
  Quantity SMALLINT, 
  Price DECIMAL(5,2),
  Picture TEXT,
  UnitID TINYINT REFERENCES tUnitType(ID)
);